// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Insights.iOS
{
	public partial class AudienceNavigationController : UINavigationController
	{
		public AudienceNavigationController (IntPtr handle) : base (handle)
		{
		}
	}
}
