// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Insights.iOS
{
	public partial class RootNavigationController : UINavigationController
	{
		public RootNavigationController (IntPtr handle) : base(handle)
		{
		}

		public override UIStatusBarStyle PreferredStatusBarStyle ()
		{
			return UIStatusBarStyle.LightContent;
		}
	}
}
