// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Insights.iOS
{
	public partial class SettingsNavigationController : UINavigationController
	{
		public SettingsNavigationController (IntPtr handle) : base (handle)
		{
		}
	}
}
