// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Insights.iOS
{
	public partial class AppsTableViewCell : UITableViewCell
	{
		public static readonly string ReuseId = "AppsTableViewCell";

		public AppsTableViewCell (IntPtr handle) : base(handle)
		{
		}

		public void SetContent (MobileApp app)
		{
			
		}
	}
}
