// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using System.Collections.Generic;

namespace Insights.iOS
{
	public partial class AppsTableViewController : UITableViewController
	{
		public List<MobileApp> Apps { get; set; }

		public AppsTableViewController (IntPtr handle) : base(handle)
		{
			Apps = InsightsService.GetApps;
		}


		public override nint NumberOfSections (UITableView tableView)
		{
			return 1;
		}


		public override nint RowsInSection (UITableView tableview, nint section)
		{
			return Apps.Count;
		}


		public override UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
		{
			var cell = tableView.DequeueReusableCell(AppsTableViewCell.ReuseId, indexPath) as AppsTableViewCell;

			var app = Apps[Convert.ToInt32(indexPath.Item)];

			cell.SetContent(app);

			return cell;
		}


		public override void RowSelected (UITableView tableView, NSIndexPath indexPath)
		{
			var tabController = Storyboard.Instantiate<AppTabBarController>();
			ShowViewController(tabController, this);
		}


		public override UIStatusBarStyle PreferredStatusBarStyle ()
		{
			return UIStatusBarStyle.LightContent;
		}
	}
}
